image: python:3

before_script:
  - VERSION=`cat angreal/VERSION`



stages:
  - unit-test
  - release
  - pages

pages:
  image: python:3
  stage: pages
  script:
    - pip install -r requirements/dev.txt
    - doit docs
    - mkdir public
    - cp -r docs/build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master

unit-test:
  image: python:3
  stage: unit-test
  script:
    - pip install -r requirements/dev.txt
    - doit tests
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  except:
    - tags

functional-test:
  image: python:3
  stage: unit-test
  script:
    - pip  install -r requirements/dev.txt
    - doit list
    - doit functional_tests
  except:
    - tags
  allow_failure: true


release:
  image: python:3
  stage: release
  before_script:
    - VERSION=`cat angreal/VERSION`
    - if ! [[ "$CI_BUILD_TAG" = "$VERSION" ]]; then echo "$VERSION does not match $CI_BUILD_TAG"; exit -1 ; fi
  script:
    - pip install -r requirements/dev.txt
    - echo "[server-login]" >> ~/.pypirc
    - echo "username="$PYPI_USER >> ~/.pypirc
    - echo "password="$PYPI_PASSWORD >> ~/.pypirc
    - python setup.py check sdist bdist_wheel upload
    - echo "" > ~/.pypirc && rm ~/.pypirc
  only:
    - tags


cleanup_release:
  stage: release
  when: always
  script:
    - rm -vf ~/.pypirc
  only:
    - tags
