image: python:3

before_script:
  - echo $HOME
  - VERSION=`cat angreal/VERSION`
  - pip install virtualenv
  - virtualenv ~/.venv/angreal
  - source ~/.venv/angreal/bin/activate
  - pip install -r requirements/dev.txt


stages:
  - test
  - release
  - pages

pages:
  image: python:3
  stage: pages
  script:
    - doit docs
    - mkdir public
    - cp -r docs/build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master

unit-test:
  image: python:3
  stage: test
  script:
    - doit tests
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  except:
    - tags

functional-test:
  image: python:3
  stage: test
  script:
     - doit functional_tests
  allow_failure: false
  except:
    - tags

install-test:
  image: python:3
  stage: test
  script:
    - pip install .
  allow_failure: false
  except:
    - tags

release:
  image: python:3
  stage: release
  before_script:
    - VERSION=`cat angreal/VERSION`
    - if ! [[ "$CI_BUILD_TAG" = "$VERSION" ]]; then echo "$VERSION does not match $CI_BUILD_TAG"; exit -1 ; fi
  script:
    - pip install -r requirements/dev.txt
    - echo "[server-login]" >> ~/.pypirc
    - echo "username="$PYPI_USER >> ~/.pypirc
    - echo "password="$PYPI_PASSWORD >> ~/.pypirc
    - python setup.py check sdist bdist_wheel upload
    - echo "" > ~/.pypirc && rm ~/.pypirc
  only:
    - tags


cleanup_release:
  stage: release
  when: always
  script:
    - rm -vf ~/.pypirc
  only:
    - tags
