image: python:3


variables:
  PYPI_USER: SECURE
  PYPI_PASSWORD: SECURE

before_script:
  - VERSION=`cat angreal/VERSION`



stages:
  - unit-test
  - release

unit-test:
  image: python:3
  stage: unit-test
  script:
    - pip install -r requirements/dev.txt
    - doit tests
    - pip install -e .
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  except:
    - tags


release:
  image: python:3
  stage: release
  before_script:
    - VERSION=`cat angreal/VERSION`
    - if ! [[ "$CI_BUILD_TAG" = "$VERSION" ]]; then echo "$VERSION does not match $CI_BUILD_TAG"; exit -1 ; fi
  script:
    - pip install -r requirements/dev.txt
    - echo "[server-login]" >> ~/.pypirc
    - echo "username=" ${PYPI_USER} >> ~/.pypirc
    - echo "password=" ${PYPI_PASSWORD} >> ~/.pypirc
    - python setup.py check sdist bdist upload
    - echo "" > ~/.pypirc && rm ~/.pypirc
  only:
    - tags


cleanup_release:
  stage: release
  when: always
  script:
    - rm -vf ~/.pypirc
  only:
    - tags
