language: python
python:
  - "3.5"
services:
  - docker
install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install coveralls

  # https://github.com/dylanbstorey/angreal/blob/travis.ci/angreal/tests/build_gitlab.sh
  - bash angreal/tests/build_gitlab.sh

script:
  # Your test script goes here
  - doit
  
after_success:
  coveralls
